version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-stretch-node-browsers-legacy
    steps:
      - checkout
      - run : mvn test
      - store_artifacts:
          path:  target
      - run:
          name: Send to CodeCov
          command: bash <(curl -s https://codecov.io/bash)

